# Generated by Django 4.1.7 on 2023-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_intership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intership',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
    ]
